# Multi-stage build to minimize production image size and security surface area.

# Stage 1: Install dependencies
FROM node:20-alpine AS deps
# Add libc6-compat for compatibility with native Node packages (e.g. sharp) on Alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy package.json and lockfile to install dependencies
COPY package.json package-lock.json* ./

# Install dependencies strictly according to the lockfile.
# Using 'npm ci' ensures a clean, repeatable install.
RUN npm ci

# Stage 2: Build the application
FROM node:20-alpine AS builder
WORKDIR /app

# Copy node_modules from deps stage and all project files
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Declare build arguments for client-side environment variables.
# Next.js embeds NEXT_PUBLIC_ variables during compile/build time.
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID

# Map build arguments to environment variables so the build process can access them
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID

# Disable Next.js telemetry during build time
ENV NEXT_TELEMETRY_DISABLED 1

# Build the Next.js application.
# This compiles typescript, generates static pages, and produces the standalone build.
RUN npm run build

# Stage 3: Run the application
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
# Disable Next.js telemetry at runtime
ENV NEXT_TELEMETRY_DISABLED 1

# Create a dedicated system user/group for security instead of running as root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy the public folder for static assets (like images, robots.txt, etc.)
COPY --from=builder /app/public ./public

# Set up the .next directory and correct ownership for the prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Copy the standalone build and static assets from builder stage.
# These paths are generated by setting `output: "standalone"` in next.config.ts.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Switch to the non-root nextjs user
USER nextjs

# Cloud Run routes incoming requests to the port specified in process.env.PORT.
# We expose port 8080 and set PORT to 8080 by default. Cloud Run will override this.
EXPOSE 8080
ENV PORT 8080

# Bind the server to all interfaces (0.0.0.0) so it is reachable from Cloud Run
ENV HOSTNAME "0.0.0.0"

# Start the application using the standalone server.
# This runs the compiled, minimal Node server directly without next CLI or devDependencies.
CMD ["node", "server.js"]
